### ISSUE TITLE
Create functions for executor

### ISSUE THREAD

**Issue by mr-bammby** [mr-bammby/ft_irc#21]
For each command create a non-member function that can be called by the executor.
- [x] NICK
- [x] USER
- [x] JOIN
- [x] PRIVMSG
- [x] NOTICE
- [x] KICK
- [x] MODE
- [x] INVITE
- [x] TOPIC
- [x] KILL
- [ ] RESTART
- [x] QUIT

**Comment by bvarlamo** [comment]
[] NICK

**Comment by SmaltSalamander** [comment]
Restart skipped
