### ISSUE TITLE
manage PING command from client

### ISSUE THREAD

**Issue by bvarlamo** [mr-bammby/ft_irc#23]
The PING message is used to test the presence of an active client at the other end of the connection.  A PING message is sent at regular intervals if no other activity detected coming from a connection.  If a connection fails to respond to a PING command within a set amount of time, that connection is closed.
Adium automatically sending ping message to server, Servers should not respond to PING commands but rely on PINGs from the other end of the connection to indicate the connection is alive.
When reciving PING message, we probably just dont have to segfault or dont take it as a wrong command. Depends how we decide, maybe also we can update some kind of time variable which indicates clients last activity.

**Comment by SuperDulli** [comment]
I will add the PING to the command list and make the parser recognize it. Then it should be easy for the executer toknow that it can safely ignore it.

**Comment by SuperDulli** [comment]
Maybe we get an issue if we just ignore a PING from a client: If it expects us to send a PONG in a certain amount of time and we dont maybe it will asume that it lost the connection or something. Let's try to see what the clients are doing if we ignore it.

**Comment by bvarlamo** [comment]
How I understand from documentation, server shouldnt respond to PING message. 
From documentation: Servers should not respond to PING commands but rely on PINGs from the other end of the connection to indicate the connection is alive.
